import Head from "next/head";
import Layout from "../components/Layout"
import Hero from "../components/Hero";
import css from "../styles/Home.module.css";
import Services from "../components/Services";
import { client } from "../lib/client";
import Menu from "../components/Menu";
 import '../node_modules/font-awesome/css/font-awesome.min.css'; 

export default function Home({ foods }) {
  
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>Indian Food Truck</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
          {/* <Services /> */}
          <Menu foods={foods} />
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "food"]';
  const foods = await client.fetch(query);
  return {
    props: {
      foods,
    },
  };
};
